# Generated by Django 2.1.3 on 2018-11-29 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation_boi', '0002_auto_20181126_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('short_description', models.CharField(max_length=250)),
                ('long_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('hat', 'Hat'), ('kitchen', 'Kitchen'), ('electronics', 'Electronics'), ('household', 'Household'), ('other', 'Other')], max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation_boi.Store')),
            ],
        ),
    ]
